name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    - name: Install dependencies
      run: dart pub get
    - name: Install example dependencies
      run: |
        cd example/flutter_usage
        flutter pub get
    - name: Analyze project
      run: dart analyze
    - name: Run tests
      run: dart test test/test_all.dart
